### ISSUE TITLE
Empty href attr 

### ISSUE THREAD

**Issue by yuchiko** [soldaran/freelancer-test.io#4]
Read this, please

> While it may be completely valid HTML to not include an href, especially with an onclick handler, there are some things to consider: it will not be keyboard-focusable without having a tabindex value set. Furthermore, this will be inaccessible to screenreader software using Internet Explorer, as IE will report through the accessibility interfaces that any anchor element without an href attribute as not-focusable, regardless of whether the tabindex has been set.
> 
> So while the following may be completely valid:
> 
> `<a class="arrow">Link content</a>`
> It's far better to explicitly add a null-effect href attribute
> 
> `<a href="javascript:void(0);" class="arrow">Link content</a>`
> For full support of all users, if you're using the class with CSS to render an image, you should also include some text content, such as the title attribute to provide a textual description of what's going on.
> 
> `<a href="javascript:void(0);" class="arrow" title="Go to linked content">Link content</a>`
> shareeditflag

[Link](http://stackoverflow.com/a/15885150/6334780)

**Comment by soldaran** [comment]
Зробив якоря a href="#"
